package types

import "errors"

var (
	ErrInvalidName                     = errors.New("name is required")
	ErrInvalidIdentifier               = errors.New("identifier must contain letters or numbers")
	ErrInvalidEmail                    = errors.New("email must be a valid email address")
	ErrInvalidPassword                 = errors.New("password must be at least 8 characters")
	ErrInvalidProjectID                = errors.New("project_id is required")
	ErrInvalidNodeID                   = errors.New("node_id is required")
	ErrInvalidServiceID                = errors.New("service_id is required")
	ErrInvalidUserID                   = errors.New("user_id is required")
	ErrNoFieldsToUpdate                = errors.New("at least one updatable field is required")
	ErrInvalidProjectMemberRole        = errors.New("role must be owner, admin, or viewer")
	ErrInvalidProjectInvitationRole    = errors.New("role must be admin or viewer")
	ErrEmptyProjectInvitations         = errors.New("at least one invitation is required")
	ErrProjectInvitationAlreadyExists  = errors.New("an active invitation already exists for this email")
	ErrMissingAgentToken               = errors.New("X-Agent-Token header is required")
	ErrInvalidAgentToken               = errors.New("invalid agent token")
	ErrUnauthenticated                 = errors.New("authentication required")
	ErrForbidden                       = errors.New("forbidden")
	ErrInvalidCredentials              = errors.New("invalid email or password")
	ErrInvalidVerificationToken        = errors.New("invalid or expired token")
	ErrInvalidProjectInvitation        = errors.New("invalid or expired invitation")
	ErrInvalidCheckType                = errors.New("check_type is required")
	ErrInvalidCheckTarget              = errors.New("check_target is required")
	ErrInvalidExecutionMode            = errors.New("execution_mode must be managed or agent")
	ErrAgentExecutionRequiresNodeID    = errors.New("node_id is required when execution_mode=agent")
	ErrManagedExecutionDisallowsNodeID = errors.New("node_id is not allowed when execution_mode=managed")
	ErrProjectNotFound                 = errors.New("project not found")
	ErrNodeNotFound                    = errors.New("node not found")
	ErrNodeMustBeAgent                 = errors.New("node must be an agent node")
	ErrServiceNotFound                 = errors.New("service not found")
	ErrSessionNotFound                 = errors.New("session not found")
	ErrProjectMemberNotFound           = errors.New("project member not found")
	ErrProjectMemberAlreadyExists      = errors.New("project member already exists")
	ErrProjectInvitationNotFound       = errors.New("project invitation not found")
	ErrCannotRemoveLastProjectOwner    = errors.New("cannot remove or demote the last owner of a project")
	ErrNodeHasServices                 = errors.New("node has services; delete services first")
	ErrUserNotFound                    = errors.New("user not found")
	ErrProjectInvitationEmailMismatch  = errors.New("invitation email does not match authenticated user")
	ErrNodeProjectMismatch             = errors.New("node does not belong to the given project")
	ErrAgentNodeMismatch               = errors.New("node_id does not match authenticated agent")
	ErrServiceProjectMismatch          = errors.New("service does not belong to the given project")
	ErrServiceNodeMismatch             = errors.New("service does not belong to the authenticated node")
)
