#!/usr/bin/env bash

set -euo pipefail

AGENT_IMAGE="ghcr.io/mariusbobitiu/agrafa-agent:latest"

SERVER_URL=""
TOKEN=""
NODE_NAME=""

usage() {
  cat <<'EOF'
Usage: agent-install.sh --server-url URL --token TOKEN [--node-name NAME]

Required flags:
  --server-url   Agrafa agent API base URL, for example https://example.com/v1
  --token        One-time agent token generated by Agrafa

Optional flags:
  --node-name    Friendly node name used for the Docker container name
  -h, --help     Show this help message
EOF
}

fail() {
  printf 'Error: %s\n\n' "$1" >&2
  usage >&2
  exit 1
}

require_value() {
  if [ $# -lt 2 ] || [ -z "${2:-}" ] || [ "${2#--}" != "$2" ]; then
    fail "Missing value for $1"
  fi
}

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf 'Error: missing required command: %s\n' "$1" >&2
    exit 1
  fi
}

sanitize_container_name() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9_.-' '-'
}

while [ $# -gt 0 ]; do
  case "$1" in
    --server-url)
      require_value "$@"
      SERVER_URL="$2"
      shift 2
      ;;
    --token)
      require_value "$@"
      TOKEN="$2"
      shift 2
      ;;
    --node-name)
      require_value "$@"
      NODE_NAME="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    --*)
      fail "Unknown flag: $1"
      ;;
    *)
      fail "Unexpected argument: $1"
      ;;
  esac
done

[ -n "$SERVER_URL" ] || fail "--server-url is required"
[ -n "$TOKEN" ] || fail "--token is required"

need_cmd docker

CONTAINER_NAME="agrafa-agent"
if [ -n "$NODE_NAME" ]; then
  SANITIZED_NAME="$(sanitize_container_name "$NODE_NAME")"
  if [ -n "$SANITIZED_NAME" ]; then
    CONTAINER_NAME="agrafa-agent-${SANITIZED_NAME}"
  fi
fi

docker run -d \
  --restart unless-stopped \
  --name "$CONTAINER_NAME" \
  --pid=host \
  -e AGRAFA_API_BASE_URL="$SERVER_URL" \
  -e AGRAFA_AGENT_TOKEN="$TOKEN" \
  -e HOST_PROC=/host/proc \
  -e HOST_SYS=/host/sys \
  -e HOST_ETC=/host/etc \
  -e HOST_ROOT=/host \
  -e AGRAFA_DISK_PATH=/host \
  -v /proc:/host/proc:ro \
  -v /sys:/host/sys:ro \
  -v /etc:/host/etc:ro \
  -v /:/host:ro \
  "$AGENT_IMAGE"

printf 'Agent container started as %s\n' "$CONTAINER_NAME"
