import { deduplicateAlerts } from "@/app/alerts/alert-presentation.ts";
import type { Alert, AlertHistoryFilters, AlertRule } from "@/types/alert.ts";
import type { ServiceAlert } from "@/types/service.ts";

export const SERVICE_OUTAGE_HISTORY_LIMIT = 10;

/**
 * Builds history filters for service outage alerts associated with a service.
 *
 * @param serviceId - The identifier of the service
 * @returns Filters for the specified service and `service_unhealthy` alerts
 */
export function serviceOutageHistoryFilters(serviceId: number): AlertHistoryFilters {
  return { serviceId, ruleType: "service_unhealthy" };
}

/**
 * Selects alerts generated by service-unhealthy rules.
 *
 * @param alerts - The alerts to filter
 * @returns Alerts whose rule type is `service_unhealthy`
 */
export function serviceOutageAlerts(alerts: readonly ServiceAlert[]) {
  return alerts.filter((alert) => alert.rule_type === "service_unhealthy");
}

/**
 * Filters out alerts for service outage rules.
 *
 * @param alerts - The alerts to filter
 * @returns Alerts whose rule type is not `service_unhealthy`
 */
export function otherServiceAlerts(alerts: readonly ServiceAlert[]) {
  return alerts.filter((alert) => alert.rule_type !== "service_unhealthy");
}

/**
 * Finds resolved outage alerts for a specific service.
 *
 * @param alerts - The alerts to search
 * @param serviceId - The service identifier to match
 * @returns The deduplicated resolved service outage alerts for the service
 */
export function resolvedServiceOutages(alerts: readonly Alert[], serviceId: number) {
  return deduplicateAlerts([...alerts]).filter(
    (alert) =>
      alert.status === "resolved" &&
      alert.rule_type === "service_unhealthy" &&
      alert.service_id === serviceId,
  );
}

/**
 * Determines whether an enabled service outage rule applies to a service.
 *
 * @param rules - The alert rules to evaluate
 * @param serviceId - The service identifier to match
 * @returns `true` if an enabled service outage rule applies globally or to the specified service, `false` otherwise.
 */
export function hasApplicableServiceOutageRule(rules: readonly AlertRule[], serviceId: number) {
  return rules.some(
    (rule) =>
      rule.is_enabled &&
      rule.rule_type === "service_unhealthy" &&
      (rule.target_scope === "all" ||
        (rule.target_scope === "specific" && rule.service_id === serviceId)),
  );
}
